### PR TITLE
add some animations, such as wave, shake,bounce,fade in, roll out…

### PR DESCRIPTION
**Pull request by ghost**
add some animations, such as wave, shake,bounce,fade in, roll out…
sample:

``` java
 EnhancedViewAnimator.animate(view).shake().duration(3000).start();
```

### CODE REVIEW

**Comment by florent37** [comment]
So cool man :+1: 
thanks for the pull request,

but why do not add them directly on the ViewAnimator ?

you can do it and add the Link:https://github.com/daimajia/AndroidViewAnimations
on the Readme

(and an author line ;) )

**Comment by gzu-liyujiang** [comment]
Because I'm sorry to break your code, so add them extends the ViewAnimator .
Thanks  your advisement, I will try do it.

**Comment by florent37** [comment]
It's not specially my code, it's open source man ;)

**Comment by florent37** [comment]
BTW thanks a lot, I send a new version today,
can you add some examples on the README ?

**Comment by florent37** [comment]
BTW thanks for your pull request :+1:

**Pull request merged**
